version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    # Eliminamos el env_file para evitar cargar el .env que tiene variables no deseadas
    # env_file:
    #   - .env
    environment:
      APP_ENV: testing
      DB_HOST: maglev.proxy.rlwy.net
      DB_PORT: "23194"
      DB_DATABASE: railway
      DB_USERNAME: root
      DB_PASSWORD: kCwqBEfywfsygCgckyRBJTcCNewgWqkz
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: easy_money
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
